// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1xlsx8e8mHIrC60tucXGh3ObBX0LyEdA',
    appId: '1:135564150467:web:7805339b3c77a21b358476',
    messagingSenderId: '135564150467',
    projectId: 'realtie-a7d85',
    authDomain: 'realtie-a7d85.firebaseapp.com',
    storageBucket: 'realtie-a7d85.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyTT-eBQcDCU9bIC5ebbN-W52goB0b6fU',
    appId: '1:135564150467:android:45e367d4053c7d69358476',
    messagingSenderId: '135564150467',
    projectId: 'realtie-a7d85',
    storageBucket: 'realtie-a7d85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSoeeZonMh38GKNEH8b88IFEIiMZx-g1U',
    appId: '1:135564150467:ios:636b955cc07b246f358476',
    messagingSenderId: '135564150467',
    projectId: 'realtie-a7d85',
    storageBucket: 'realtie-a7d85.appspot.com',
    iosBundleId: 'com.example.messenger',
  );
}
